-- Rename messages table
ALTER TABLE PREFIX_mailer_messages RENAME TO PREFIX_mailer_messages_old;

-- Schema generated by Doctrine2
CREATE TABLE PREFIX_mailer_messages (
  message_id BIGINT NOT NULL, campaign_id INT DEFAULT NULL, priority SMALLINT DEFAULT 0 NOT NULL, created_at INT NOT NULL, locked_at INT DEFAULT NULL, sent_at INT DEFAULT NULL, read_at INT DEFAULT NULL, failed_at INT DEFAULT NULL, fail_count SMALLINT DEFAULT 0 NOT NULL, status VARCHAR(32) NOT NULL, lock_key VARCHAR(64) DEFAULT NULL, tracking_key VARCHAR(64) DEFAULT NULL, reply_to_email VARCHAR(255) DEFAULT NULL, reply_to_name VARCHAR(255) DEFAULT NULL, recipient_email VARCHAR(255) NOT NULL, recipient_name VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) NOT NULL, content_type VARCHAR(16) NOT NULL, content TEXT NOT NULL, PRIMARY KEY(message_id));

CREATE INDEX IDX_AC84384EF639F774 ON PREFIX_mailer_messages (campaign_id);

CREATE INDEX IDX_AC84384E7B00651C62A6DC278B ON PREFIX_mailer_messages (status, priority, created_at);

CREATE UNIQUE INDEX KEY_AC84384E19A50076 ON PREFIX_mailer_messages (lock_key);

CREATE UNIQUE INDEX KEY_AC84384ECDE0581A ON PREFIX_mailer_messages (tracking_key);

CREATE SEQUENCE PREFIX_mailer_messages_message_id_seq INCREMENT BY 1 MINVALUE 1 START 1;

ALTER TABLE PREFIX_mailer_messages ADD CONSTRAINT FK_AC84384EF639F774 FOREIGN KEY (campaign_id) REFERENCES PREFIX_mailer_campaigns (campaign_id) NOT DEFERRABLE INITIALLY IMMEDIATE;

-- Import data from old messages
INSERT INTO PREFIX_mailer_messages (
  message_id, campaign_id, created_at, locked_at, sent_at, read_at, priority,
  fail_count, status, lock_key, tracking_key, reply_to_email, reply_to_name,
  recipient_email, recipient_name, subject, content_type, content
)
    SELECT
      message.message_id, campaign_id, created_at, locked_at, sent_at, read_at,
      priority, fail_count, status, lock_key, tracking_key, reply_to_email,
      reply_to_name, recipient.email, recipient.name, subject, content_type, content
    FROM PREFIX_mailer_messages_old message
    JOIN PREFIX_mailer_recipients recipient ON recipient.message_id = message.message_id
    ORDER BY message.message_id
;
